/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApiConfig {
  'apiBaseUrl' : string,
  'lastScrapeTime' : [] | [Timestamp],
}
export interface Category {
  'type_name' : string,
  'type_pid' : TypeId,
  'type_id' : TypeId,
}
export interface PaginatedVideos {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<VideoInfo>,
}
export type ScrapeStatus = { 'idle' : null } |
  { 'completed' : { 'totalVideos' : bigint, 'totalCategories' : bigint } } |
  { 'error' : string } |
  { 'running' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type TypeId = bigint;
export interface VideoInfo {
  'type_name' : string,
  'vod_remarks' : string,
  'vod_area' : string,
  'vod_id' : VodId,
  'vod_name' : string,
  'vod_actor' : string,
  'vod_pic' : string,
  'vod_year' : string,
  'vod_content' : string,
  'vod_score' : string,
  'vod_play_url' : string,
  'vod_play_from' : string,
  'vod_director' : string,
  'type_id' : TypeId,
}
export interface VideoUpdateFields {
  'type_name' : [] | [string],
  'vod_remarks' : [] | [string],
  'vod_area' : [] | [string],
  'vod_name' : [] | [string],
  'vod_actor' : [] | [string],
  'vod_pic' : [] | [string],
  'vod_year' : [] | [string],
  'vod_content' : [] | [string],
  'vod_score' : [] | [string],
  'vod_play_url' : [] | [string],
  'vod_play_from' : [] | [string],
  'vod_director' : [] | [string],
}
export type VodId = bigint;
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'claimOwner' : ActorMethod<[], boolean>,
  'deleteVideo' : ActorMethod<[VodId], boolean>,
  'getApiConfig' : ActorMethod<[], ApiConfig>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getScrapeStatus' : ActorMethod<[], ScrapeStatus>,
  'getVideoById' : ActorMethod<[VodId], [] | [VideoInfo]>,
  'getVideosByCategory' : ActorMethod<
    [TypeId, bigint, bigint],
    PaginatedVideos
  >,
  'searchVideos' : ActorMethod<[string], Array<VideoInfo>>,
  'setApiConfig' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'triggerScrape' : ActorMethod<[], undefined>,
  'updateVideo' : ActorMethod<[VodId, VideoUpdateFields], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];