/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VodId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ApiConfig = IDL.Record({
  'apiBaseUrl' : IDL.Text,
  'lastScrapeTime' : IDL.Opt(Timestamp),
});
export const TypeId = IDL.Nat;
export const Category = IDL.Record({
  'type_name' : IDL.Text,
  'type_pid' : TypeId,
  'type_id' : TypeId,
});
export const ScrapeStatus = IDL.Variant({
  'idle' : IDL.Null,
  'completed' : IDL.Record({
    'totalVideos' : IDL.Nat,
    'totalCategories' : IDL.Nat,
  }),
  'error' : IDL.Text,
  'running' : IDL.Null,
});
export const VideoInfo = IDL.Record({
  'type_name' : IDL.Text,
  'vod_remarks' : IDL.Text,
  'vod_area' : IDL.Text,
  'vod_id' : VodId,
  'vod_name' : IDL.Text,
  'vod_actor' : IDL.Text,
  'vod_pic' : IDL.Text,
  'vod_year' : IDL.Text,
  'vod_content' : IDL.Text,
  'vod_score' : IDL.Text,
  'vod_play_url' : IDL.Text,
  'vod_play_from' : IDL.Text,
  'vod_director' : IDL.Text,
  'type_id' : TypeId,
});
export const PaginatedVideos = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(VideoInfo),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const VideoUpdateFields = IDL.Record({
  'type_name' : IDL.Opt(IDL.Text),
  'vod_remarks' : IDL.Opt(IDL.Text),
  'vod_area' : IDL.Opt(IDL.Text),
  'vod_name' : IDL.Opt(IDL.Text),
  'vod_actor' : IDL.Opt(IDL.Text),
  'vod_pic' : IDL.Opt(IDL.Text),
  'vod_year' : IDL.Opt(IDL.Text),
  'vod_content' : IDL.Opt(IDL.Text),
  'vod_score' : IDL.Opt(IDL.Text),
  'vod_play_url' : IDL.Opt(IDL.Text),
  'vod_play_from' : IDL.Opt(IDL.Text),
  'vod_director' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'claimOwner' : IDL.Func([], [IDL.Bool], []),
  'deleteVideo' : IDL.Func([VodId], [IDL.Bool], []),
  'getApiConfig' : IDL.Func([], [ApiConfig], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getScrapeStatus' : IDL.Func([], [ScrapeStatus], ['query']),
  'getVideoById' : IDL.Func([VodId], [IDL.Opt(VideoInfo)], ['query']),
  'getVideosByCategory' : IDL.Func(
      [TypeId, IDL.Nat, IDL.Nat],
      [PaginatedVideos],
      ['query'],
    ),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoInfo)], ['query']),
  'setApiConfig' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerScrape' : IDL.Func([], [], []),
  'updateVideo' : IDL.Func([VodId, VideoUpdateFields], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VodId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ApiConfig = IDL.Record({
    'apiBaseUrl' : IDL.Text,
    'lastScrapeTime' : IDL.Opt(Timestamp),
  });
  const TypeId = IDL.Nat;
  const Category = IDL.Record({
    'type_name' : IDL.Text,
    'type_pid' : TypeId,
    'type_id' : TypeId,
  });
  const ScrapeStatus = IDL.Variant({
    'idle' : IDL.Null,
    'completed' : IDL.Record({
      'totalVideos' : IDL.Nat,
      'totalCategories' : IDL.Nat,
    }),
    'error' : IDL.Text,
    'running' : IDL.Null,
  });
  const VideoInfo = IDL.Record({
    'type_name' : IDL.Text,
    'vod_remarks' : IDL.Text,
    'vod_area' : IDL.Text,
    'vod_id' : VodId,
    'vod_name' : IDL.Text,
    'vod_actor' : IDL.Text,
    'vod_pic' : IDL.Text,
    'vod_year' : IDL.Text,
    'vod_content' : IDL.Text,
    'vod_score' : IDL.Text,
    'vod_play_url' : IDL.Text,
    'vod_play_from' : IDL.Text,
    'vod_director' : IDL.Text,
    'type_id' : TypeId,
  });
  const PaginatedVideos = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(VideoInfo),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const VideoUpdateFields = IDL.Record({
    'type_name' : IDL.Opt(IDL.Text),
    'vod_remarks' : IDL.Opt(IDL.Text),
    'vod_area' : IDL.Opt(IDL.Text),
    'vod_name' : IDL.Opt(IDL.Text),
    'vod_actor' : IDL.Opt(IDL.Text),
    'vod_pic' : IDL.Opt(IDL.Text),
    'vod_year' : IDL.Opt(IDL.Text),
    'vod_content' : IDL.Opt(IDL.Text),
    'vod_score' : IDL.Opt(IDL.Text),
    'vod_play_url' : IDL.Opt(IDL.Text),
    'vod_play_from' : IDL.Opt(IDL.Text),
    'vod_director' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'claimOwner' : IDL.Func([], [IDL.Bool], []),
    'deleteVideo' : IDL.Func([VodId], [IDL.Bool], []),
    'getApiConfig' : IDL.Func([], [ApiConfig], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getScrapeStatus' : IDL.Func([], [ScrapeStatus], ['query']),
    'getVideoById' : IDL.Func([VodId], [IDL.Opt(VideoInfo)], ['query']),
    'getVideosByCategory' : IDL.Func(
        [TypeId, IDL.Nat, IDL.Nat],
        [PaginatedVideos],
        ['query'],
      ),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoInfo)], ['query']),
    'setApiConfig' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerScrape' : IDL.Func([], [], []),
    'updateVideo' : IDL.Func([VodId, VideoUpdateFields], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };