/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PaginatedVideos {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<VideoInfo>;
}
export interface VideoUpdateFields {
    type_name?: string;
    vod_remarks?: string;
    vod_area?: string;
    vod_name?: string;
    vod_actor?: string;
    vod_pic?: string;
    vod_year?: string;
    vod_content?: string;
    vod_score?: string;
    vod_play_url?: string;
    vod_play_from?: string;
    vod_director?: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Timestamp = bigint;
export type ScrapeStatus = {
    __kind__: "idle";
    idle: null;
} | {
    __kind__: "completed";
    completed: {
        totalVideos: bigint;
        totalCategories: bigint;
    };
} | {
    __kind__: "error";
    error: string;
} | {
    __kind__: "running";
    running: null;
};
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Category {
    type_name: string;
    type_pid: TypeId;
    type_id: TypeId;
}
export interface ApiConfig {
    apiBaseUrl: string;
    lastScrapeTime?: Timestamp;
}
export type VodId = bigint;
export interface VideoInfo {
    type_name: string;
    vod_remarks: string;
    vod_area: string;
    vod_id: VodId;
    vod_name: string;
    vod_actor: string;
    vod_pic: string;
    vod_year: string;
    vod_content: string;
    vod_score: string;
    vod_play_url: string;
    vod_play_from: string;
    vod_director: string;
    type_id: TypeId;
}
export interface http_header {
    value: string;
    name: string;
}
export type TypeId = bigint;
export interface backendInterface {
    claimOwner(): Promise<boolean>;
    deleteVideo(vodId: VodId): Promise<boolean>;
    getApiConfig(): Promise<ApiConfig>;
    getCategories(): Promise<Array<Category>>;
    getScrapeStatus(): Promise<ScrapeStatus>;
    getVideoById(vodId: VodId): Promise<VideoInfo | null>;
    getVideosByCategory(typeId: TypeId, page: bigint, pageSize: bigint): Promise<PaginatedVideos>;
    searchVideos(keyword: string): Promise<Array<VideoInfo>>;
    setApiConfig(url: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    triggerScrape(): Promise<void>;
    updateVideo(vodId: VodId, fields: VideoUpdateFields): Promise<boolean>;
}
import type { ApiConfig as _ApiConfig, ScrapeStatus as _ScrapeStatus, Timestamp as _Timestamp, VideoInfo as _VideoInfo, VideoUpdateFields as _VideoUpdateFields } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async claimOwner(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimOwner();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimOwner();
            return result;
        }
    }
    async deleteVideo(arg0: VodId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async getApiConfig(): Promise<ApiConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiConfig();
                return from_candid_ApiConfig_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiConfig();
            return from_candid_ApiConfig_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getScrapeStatus(): Promise<ScrapeStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getScrapeStatus();
                return from_candid_ScrapeStatus_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScrapeStatus();
            return from_candid_ScrapeStatus_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoById(arg0: VodId): Promise<VideoInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoById(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoById(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideosByCategory(arg0: TypeId, arg1: bigint, arg2: bigint): Promise<PaginatedVideos> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async searchVideos(arg0: string): Promise<Array<VideoInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchVideos(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchVideos(arg0);
            return result;
        }
    }
    async setApiConfig(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApiConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApiConfig(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async triggerScrape(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerScrape();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerScrape();
            return result;
        }
    }
    async updateVideo(arg0: VodId, arg1: VideoUpdateFields): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideo(arg0, to_candid_VideoUpdateFields_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideo(arg0, to_candid_VideoUpdateFields_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApiConfig_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiConfig): ApiConfig {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_ScrapeStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScrapeStatus): ScrapeStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoInfo]): VideoInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    apiBaseUrl: string;
    lastScrapeTime: [] | [_Timestamp];
}): {
    apiBaseUrl: string;
    lastScrapeTime?: Timestamp;
} {
    return {
        apiBaseUrl: value.apiBaseUrl,
        lastScrapeTime: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.lastScrapeTime))
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    idle: null;
} | {
    completed: {
        totalVideos: bigint;
        totalCategories: bigint;
    };
} | {
    error: string;
} | {
    running: null;
}): {
    __kind__: "idle";
    idle: null;
} | {
    __kind__: "completed";
    completed: {
        totalVideos: bigint;
        totalCategories: bigint;
    };
} | {
    __kind__: "error";
    error: string;
} | {
    __kind__: "running";
    running: null;
} {
    return "idle" in value ? {
        __kind__: "idle",
        idle: value.idle
    } : "completed" in value ? {
        __kind__: "completed",
        completed: value.completed
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "running" in value ? {
        __kind__: "running",
        running: value.running
    } : value;
}
function to_candid_VideoUpdateFields_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoUpdateFields): _VideoUpdateFields {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    type_name?: string;
    vod_remarks?: string;
    vod_area?: string;
    vod_name?: string;
    vod_actor?: string;
    vod_pic?: string;
    vod_year?: string;
    vod_content?: string;
    vod_score?: string;
    vod_play_url?: string;
    vod_play_from?: string;
    vod_director?: string;
}): {
    type_name: [] | [string];
    vod_remarks: [] | [string];
    vod_area: [] | [string];
    vod_name: [] | [string];
    vod_actor: [] | [string];
    vod_pic: [] | [string];
    vod_year: [] | [string];
    vod_content: [] | [string];
    vod_score: [] | [string];
    vod_play_url: [] | [string];
    vod_play_from: [] | [string];
    vod_director: [] | [string];
} {
    return {
        type_name: value.type_name ? candid_some(value.type_name) : candid_none(),
        vod_remarks: value.vod_remarks ? candid_some(value.vod_remarks) : candid_none(),
        vod_area: value.vod_area ? candid_some(value.vod_area) : candid_none(),
        vod_name: value.vod_name ? candid_some(value.vod_name) : candid_none(),
        vod_actor: value.vod_actor ? candid_some(value.vod_actor) : candid_none(),
        vod_pic: value.vod_pic ? candid_some(value.vod_pic) : candid_none(),
        vod_year: value.vod_year ? candid_some(value.vod_year) : candid_none(),
        vod_content: value.vod_content ? candid_some(value.vod_content) : candid_none(),
        vod_score: value.vod_score ? candid_some(value.vod_score) : candid_none(),
        vod_play_url: value.vod_play_url ? candid_some(value.vod_play_url) : candid_none(),
        vod_play_from: value.vod_play_from ? candid_some(value.vod_play_from) : candid_none(),
        vod_director: value.vod_director ? candid_some(value.vod_director) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
